[package]
name = "subhost-consensus"
description = "DAG dissemination, HotStuff quorum rules and staking for Subhost Web3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
subhost-core = { workspace = true }
subhost-crypto = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-serialize = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
